###################################################################

# Created by write_sdc on Sat Nov 29 08:24:11 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max WCCOM -max_library                               \
fsa0m_a_generic_core_ss1p62v125c\
                         -min BCCOM -min_library                               \
fsa0m_a_generic_core_ff1p98vm40c
#set_wire_load_mode top
#set_wire_load_model -name G50K -library fsa0m_a_generic_core_ff1p98vm40c
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports clk]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports rst_n]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports in_valid_data]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {data[7]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {data[6]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {data[5]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {data[4]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {data[3]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {data[2]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {data[1]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {data[0]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports in_valid_cmd]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[17]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[16]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[15]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[14]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[13]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[12]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[11]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[10]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[9]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[8]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[7]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[6]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[5]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[4]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[3]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[2]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[1]}]
set_driving_cell -lib_cell XMD -library fsa0m_a_t33_generic_io_ss1p62v125c     \
-pin O [get_ports {cmd[0]}]
set_load -pin_load 0.024119 [get_ports busy]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports in_valid_data]
set_max_capacitance 0.15 [get_ports {data[7]}]
set_max_capacitance 0.15 [get_ports {data[6]}]
set_max_capacitance 0.15 [get_ports {data[5]}]
set_max_capacitance 0.15 [get_ports {data[4]}]
set_max_capacitance 0.15 [get_ports {data[3]}]
set_max_capacitance 0.15 [get_ports {data[2]}]
set_max_capacitance 0.15 [get_ports {data[1]}]
set_max_capacitance 0.15 [get_ports {data[0]}]
set_max_capacitance 0.15 [get_ports in_valid_cmd]
set_max_capacitance 0.15 [get_ports {cmd[17]}]
set_max_capacitance 0.15 [get_ports {cmd[16]}]
set_max_capacitance 0.15 [get_ports {cmd[15]}]
set_max_capacitance 0.15 [get_ports {cmd[14]}]
set_max_capacitance 0.15 [get_ports {cmd[13]}]
set_max_capacitance 0.15 [get_ports {cmd[12]}]
set_max_capacitance 0.15 [get_ports {cmd[11]}]
set_max_capacitance 0.15 [get_ports {cmd[10]}]
set_max_capacitance 0.15 [get_ports {cmd[9]}]
set_max_capacitance 0.15 [get_ports {cmd[8]}]
set_max_capacitance 0.15 [get_ports {cmd[7]}]
set_max_capacitance 0.15 [get_ports {cmd[6]}]
set_max_capacitance 0.15 [get_ports {cmd[5]}]
set_max_capacitance 0.15 [get_ports {cmd[4]}]
set_max_capacitance 0.15 [get_ports {cmd[3]}]
set_max_capacitance 0.15 [get_ports {cmd[2]}]
set_max_capacitance 0.15 [get_ports {cmd[1]}]
set_max_capacitance 0.15 [get_ports {cmd[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports in_valid_data]
set_max_fanout 10 [get_ports {data[7]}]
set_max_fanout 10 [get_ports {data[6]}]
set_max_fanout 10 [get_ports {data[5]}]
set_max_fanout 10 [get_ports {data[4]}]
set_max_fanout 10 [get_ports {data[3]}]
set_max_fanout 10 [get_ports {data[2]}]
set_max_fanout 10 [get_ports {data[1]}]
set_max_fanout 10 [get_ports {data[0]}]
set_max_fanout 10 [get_ports in_valid_cmd]
set_max_fanout 10 [get_ports {cmd[17]}]
set_max_fanout 10 [get_ports {cmd[16]}]
set_max_fanout 10 [get_ports {cmd[15]}]
set_max_fanout 10 [get_ports {cmd[14]}]
set_max_fanout 10 [get_ports {cmd[13]}]
set_max_fanout 10 [get_ports {cmd[12]}]
set_max_fanout 10 [get_ports {cmd[11]}]
set_max_fanout 10 [get_ports {cmd[10]}]
set_max_fanout 10 [get_ports {cmd[9]}]
set_max_fanout 10 [get_ports {cmd[8]}]
set_max_fanout 10 [get_ports {cmd[7]}]
set_max_fanout 10 [get_ports {cmd[6]}]
set_max_fanout 10 [get_ports {cmd[5]}]
set_max_fanout 10 [get_ports {cmd[4]}]
set_max_fanout 10 [get_ports {cmd[3]}]
set_max_fanout 10 [get_ports {cmd[2]}]
set_max_fanout 10 [get_ports {cmd[1]}]
set_max_fanout 10 [get_ports {cmd[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports in_valid_data]
set_max_transition 3 [get_ports {data[7]}]
set_max_transition 3 [get_ports {data[6]}]
set_max_transition 3 [get_ports {data[5]}]
set_max_transition 3 [get_ports {data[4]}]
set_max_transition 3 [get_ports {data[3]}]
set_max_transition 3 [get_ports {data[2]}]
set_max_transition 3 [get_ports {data[1]}]
set_max_transition 3 [get_ports {data[0]}]
set_max_transition 3 [get_ports in_valid_cmd]
set_max_transition 3 [get_ports {cmd[17]}]
set_max_transition 3 [get_ports {cmd[16]}]
set_max_transition 3 [get_ports {cmd[15]}]
set_max_transition 3 [get_ports {cmd[14]}]
set_max_transition 3 [get_ports {cmd[13]}]
set_max_transition 3 [get_ports {cmd[12]}]
set_max_transition 3 [get_ports {cmd[11]}]
set_max_transition 3 [get_ports {cmd[10]}]
set_max_transition 3 [get_ports {cmd[9]}]
set_max_transition 3 [get_ports {cmd[8]}]
set_max_transition 3 [get_ports {cmd[7]}]
set_max_transition 3 [get_ports {cmd[6]}]
set_max_transition 3 [get_ports {cmd[5]}]
set_max_transition 3 [get_ports {cmd[4]}]
set_max_transition 3 [get_ports {cmd[3]}]
set_max_transition 3 [get_ports {cmd[2]}]
set_max_transition 3 [get_ports {cmd[1]}]
set_max_transition 3 [get_ports {cmd[0]}]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 5  [get_ports in_valid_data]
set_input_delay -clock clk  -min 0  [get_ports in_valid_data]
set_input_delay -clock clk  -max 5  [get_ports {data[7]}]
set_input_delay -clock clk  -min 0  [get_ports {data[7]}]
set_input_delay -clock clk  -max 5  [get_ports {data[6]}]
set_input_delay -clock clk  -min 0  [get_ports {data[6]}]
set_input_delay -clock clk  -max 5  [get_ports {data[5]}]
set_input_delay -clock clk  -min 0  [get_ports {data[5]}]
set_input_delay -clock clk  -max 5  [get_ports {data[4]}]
set_input_delay -clock clk  -min 0  [get_ports {data[4]}]
set_input_delay -clock clk  -max 5  [get_ports {data[3]}]
set_input_delay -clock clk  -min 0  [get_ports {data[3]}]
set_input_delay -clock clk  -max 5  [get_ports {data[2]}]
set_input_delay -clock clk  -min 0  [get_ports {data[2]}]
set_input_delay -clock clk  -max 5  [get_ports {data[1]}]
set_input_delay -clock clk  -min 0  [get_ports {data[1]}]
set_input_delay -clock clk  -max 5  [get_ports {data[0]}]
set_input_delay -clock clk  -min 0  [get_ports {data[0]}]
set_input_delay -clock clk  -max 5  [get_ports in_valid_cmd]
set_input_delay -clock clk  -min 0  [get_ports in_valid_cmd]
set_input_delay -clock clk  -max 5  [get_ports {cmd[17]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[17]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[16]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[16]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[15]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[15]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[14]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[14]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[13]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[13]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[12]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[12]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[11]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[11]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[10]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[10]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[9]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[9]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[8]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[8]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[7]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[7]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[6]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[6]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[5]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[5]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[4]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[4]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[3]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[3]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[2]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[2]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[1]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[1]}]
set_input_delay -clock clk  -max 5  [get_ports {cmd[0]}]
set_input_delay -clock clk  -min 0  [get_ports {cmd[0]}]
set_output_delay -clock clk  -max 5  [get_ports busy]
set_output_delay -clock clk  -min 0  [get_ports busy]
