###############################################################
#  Generated by:      Cadence Innovus 20.15-s105_1
#  OS:                Linux x86_64(Host ID ee21)
#  Generated on:      Mon Jul 31 20:58:48 2023
#  Design:            CHIP
#  Command:           saveIoFile -byOrder CHIP.io
###############################################################

###############################################################
#  You can modify by your own
#  You can modify by your own
#  You can modify by your own
###############################################################

# Syntax: 
#(inst  name="PAD_NAME"	  place_status=placed )
#(endspace gap=50)

(globals
    version = 3
	space = 31
    io_order = default
)

(iopad
    (top
        (inst name="VDDP0" place_status=placed)
        (inst name="I_cmd8" place_status=placed)
        (inst name="VDDC0" place_status=placed)
        (inst name="I_cmd9" place_status=placed)
        (inst name="VDDP4" place_status=placed)
        (inst name="I_data0" place_status=placed)
        (inst name="GNDP4" place_status=placed)
        (inst name="I_cmd0" place_status=placed)
        (inst name="GNDP0" place_status=placed)
        (inst name="I_cmd10" place_status=placed)
        (inst name="GNDC0" place_status=placed)
        (inst name="I_cmd11" place_status=placed)
        (inst name="VDDP1" place_status=placed)
        (inst name="I_cmd12" place_status=placed)
        (endspace gap=50)
    )
    (right
        (inst name="VDDC1" place_status=placed)
        (inst name="I_cmd13" place_status=placed)
        (inst name="VDDP5" place_status=placed)
        (inst name="I_data1" place_status=placed)
        (inst name="GNDP5" place_status=placed)
        (inst name="I_cmd1" place_status=placed)
        (inst name="GNDP1" place_status=placed)
        (inst name="I_cmd14" place_status=placed)
        (inst name="GNDC1" place_status=placed)
        (inst name="I_cmd15" place_status=placed)
        (inst name="VDDP2" place_status=placed)
        (inst name="I_cmd16" place_status=placed)
        (inst name="VDDC2" place_status=placed)
        (inst name="I_cmd17" place_status=placed)
        (endspace gap=50)
    )
    (bottom
        (inst name="I_data2" place_status=placed)
        (inst name="I_cmd2" place_status=placed)
        (inst name="GNDP2" place_status=placed)
        (inst name="VDDC4" place_status=placed)
        (inst name="GNDC2" place_status=placed)
        (inst name="VDDP3" place_status=placed)
        (inst name="VDDC3" place_status=placed)
        (inst name="I_data3" place_status=placed)
        (inst name="GNDC4" place_status=placed)
        (inst name="I_cmd3" place_status=placed)
        (inst name="GNDP3" place_status=placed)
        (inst name="GNDC3" place_status=placed)`
        (inst name="I_data4" place_status=placed)
        (inst name="O_busy" place_status=placed)
        (endspace gap=50)
    )
    (left
        (inst name="I_cmd4" place_status=placed)
        (inst name="I_data5" place_status=placed)
        (inst name="VDDC5" place_status=placed)
        (inst name="I_CLK" place_status=placed)
        (inst name="I_cmd5" place_status=placed)
        (inst name="I_data6" place_status=placed)
        (inst name="I_RST" place_status=placed)
        (inst name="GNDC5" place_status=placed)
        (inst name="I_cmd6" place_status=placed)
        (inst name="I_data7" place_status=placed)
        (inst name="I_in_valid_data" place_status=placed) 
        (inst name="I_cmd7" place_status=placed)
        (inst name="I_in_valid_cmd" place_status=placed)
        (endspace gap=50)
    )
    (topright
        (inst name="topright" cell="CORNERD")
    )
    (topleft
        (inst name="topleft" cell="CORNERD")
    )
    (bottomright
        (inst name="bottomright" cell="CORNERD")
    )
    (bottomleft
        (inst name="bottomleft" cell="CORNERD")
    )
)